# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Shubhanshu Singh
title: Machine Learning Engineer
email: mpsshubhanshu.123@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: TheCuriousLad
github_username:  shubhanshu1995
# dribbble_username: jekyll
facebook_username: shubhanshu1995
# flickr_username: jekyll
instagram_username: shubhanshu._.singh
linkedin_username: shubhanshu001
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a machine learning engineer who loves to play with data. I also have experience in making software and web apps.

  I am most skilled in : <mark>Python</mark> <mark>C++</mark> <mark>Machine Learning</mark> <mark>Data Structures and Algorithms</mark> and <mark>Django</mark>

  AREA OF INTEREST : <mark>Natural Language Processing</mark> <mark>Deep Learning</mark> <mark>Computer Vision</mark> <mark>Machine Learning</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Trainings and Certifications Section
# trainings_title: Trainings and Certifications  

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Machine Learning and software engineering some of my other interests and hobbies are:
   - DC Comics Fan but I like Marvel too !!
   - Cooking
   - Reading Books
   - Quora addict
   - Yoga Practitioner
   - Elliot Alderson Fan (Mr Robot TV Series)
   - Binge watching Netflix

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
