- layout: top-middle
  name: Neural Networks and Deep Learning
  dates: February 2020
  qualification: By Andrew NG, Deeplearning.ai, Coursera

- layout: top-middle
  name: Machine Learning A - Z, Udemy
  dates: September 2020
  qualification: By Kirill Eremenko & Hadelin De Ponteves
