- layout: top-middle
  name: Deep Learning Specialization
  dates: May 2020
  qualification: By Andrew NG, Deeplearning.ai, Coursera

- layout: top-middle
  name: Machine Learning
  dates: April 2020
  qualification: By Andrew NG, Stanford University, Coursera

- layout: top-middle
  name: Machine Learning A - Z, Udemy
  dates: June 2020
  qualification: By Kirill Eremenko & Hadelin De Ponteves
